"""add_vehicles_deliveries_tracking_events

Revision ID: ad24198ff5fd
Revises: 65a79222c302
Create Date: 2026-06-24 11:49:27.769927

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ad24198ff5fd"
down_revision: Union[str, None] = "65a79222c302"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vehicles",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("plate", sa.String(length=10), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("type", sa.Enum("truck", "van", "motorcycle", "car", name="vehicle_type"), nullable=False),
        sa.Column("driver_name", sa.String(length=100), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_vehicles_plate"), "vehicles", ["plate"], unique=True)
    op.create_table(
        "deliveries",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("tracking_code", sa.String(length=50), nullable=False),
        sa.Column("sender_name", sa.String(length=100), nullable=False),
        sa.Column("sender_address", sa.String(length=255), nullable=False),
        sa.Column("recipient_name", sa.String(length=100), nullable=False),
        sa.Column("recipient_address", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "in_transit", "delivered", "failed", "returned", name="delivery_status"),
            nullable=False,
        ),
        sa.Column("vehicle_id", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["vehicle_id"],
            ["vehicles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_deliveries_tracking_code"), "deliveries", ["tracking_code"], unique=True)
    op.create_table(
        "tracking_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("delivery_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "in_transit", "delivered", "failed", "returned", name="delivery_status"),
            nullable=False,
        ),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(
            ["delivery_id"],
            ["deliveries.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tracking_events_delivery_id"), "tracking_events", ["delivery_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tracking_events_delivery_id"), table_name="tracking_events")
    op.drop_table("tracking_events")
    op.drop_index(op.f("ix_deliveries_tracking_code"), table_name="deliveries")
    op.drop_table("deliveries")
    op.drop_index(op.f("ix_vehicles_plate"), table_name="vehicles")
    op.drop_table("vehicles")
    # ### end Alembic commands ###
